### ISSUE TITLE
showkase browser is not showing component from submodule

### ISSUE THREAD

**Issue by vivart** [airbnb/Showkase#213] opened 2022-01-21 16:48 UTC
In multi module project structure, showkase browser is showing components only from the module where I have @ShowkaseRoot it's ignoring all compassable from submodules.

**Comment by vinaygaba** [comment] 2022-01-22 17:26
Were you using ksp by any chance? I think there might've been a regression after we added ksp support. Can you give me more details about how this is setup.

**Comment by vivart** [comment] 2022-01-23 10:57
I am not using ksp. In my project (app -> module a -> module b), I have added showkase dependencies to both the modules and I have added @ShowkaseRoot to module a.  Showkase browser is showing all the components from module a but not showing anything from module b.

**Comment by Chrisjc28** [comment] 2022-01-24 08:50
I have the same issue and raised this as part of a closed issue https://github.com/airbnb/Showkase/issues/205#issue-1103813910 - i might not have provided enough information the first time but to give more information this time i have a kotlin gradle script for each module - i have only one ShowkaseRootModule defined in the base module `app` and the other modules have got the correct dependencies 
```
implementation("com.airbnb.android:showkase:1.0.0-beta10")
kapt("com.airbnb.android:showkase-processor:1.0.0-beta10")
``` 

```
@ShowkaseRoot
class AppShowCaseModule : ShowkaseRootModule
```

```
@ShowkaseColor(name = "Shade1")
val Shade1 = Color(0xFFF4F5F7)
```

The color values annotated with @ShowkaseColor is in my other module so app isn't pulling from this module.

**Comment by Chrisjc28** [comment] 2022-01-24 09:15
If this helps i downgraded to `1.0.0-beta08` and it seems to be working now

**Comment by Chrisjc28** [comment] 2022-01-24 09:16
Above `1.0.0-beta08` seems to fail to pull through the other modules components

**Comment by vinaygaba** [comment] 2022-01-24 17:37
Okay I think we have enough reports to know something broke when doing the KSP refactor. I'll be investigating this today and will keep y'all posted!

**Comment by vinaygaba** [comment] 2022-01-24 20:38
Alright I have a fix for this - https://github.com/airbnb/Showkase/pull/216

**Closed** 2022-01-28 03:28 UTC

**Comment by davidvavra** [comment] 2022-02-04 12:35
Can we get this released please?

**Comment by vinaygaba** [comment] 2022-02-04 20:38
You can use this release - https://github.com/airbnb/Showkase/releases/tag/1.0.0-beta11
