### ISSUE TITLE
Unresolved reference: getBrowserIntent

### ISSUE THREAD

**Issue by hamedsilver** [airbnb/Showkase#265] opened 2022-09-12 13:15 UTC
I'am adding showkase-processor with KSP 
but get Unresolved reference: getBrowserIntent

I'm using Showkase In multi module way:

app module:
     * just use Theme and start showCase Activity*
        setContent {
            startActivity(Showkase.getBrowserIntent(this))
            finish()
        }

ui_core module(android Library module):
     *contain Compose components and Theme*

in both module I added the show Case dependencies
I check the generated file's in app module and find RootModuleShowkaseExtensionFunctionsCodegen

I used the implementation of the function directly inn my code for starting the Activity and it works.

    val intent = Intent(context, ShowkaseBrowserActivity::class.java)
    intent.putExtra("SHOWKASE_ROOT_MODULE", "com.mydigipay.designsystem.RootModule")

**Comment by zaaaach** [comment] 2022-09-16 20:02
I am getting the exact same thing using KSP.

**Comment by vinaygaba** [comment] 2022-09-16 20:17
Are you trying to reference the `getBrowserIntent` in the same module that you declared the `@ShowkaseRoot` class in?

```
@ShowkaseRoot
class MyRootModule: ShowkaseRootModule
```

**Comment by zaaaach** [comment] 2022-09-16 20:34
> Are you trying to reference the `getBrowserIntent` in the same module that you declared the `@ShowkaseRoot` class in?
> 
> ```
> @ShowkaseRoot
> class MyRootModule: ShowkaseRootModule
> ```

Yes. I added an identical `RootModule.kt` as in the sample. I can also see the code is being generated in the `build` folder and `getBrowserIntent` exists.

**Comment by vinaygaba** [comment] 2022-09-18 03:38
If the file is correctly generated with the `getBrowserIntent`, there's no reason for you to not be able to access it, unless you are trying to access it from a different package. Can you show me what the generated file that contains the `getBrowserIntent` looks like?

**Comment by zaaaach** [comment] 2022-09-20 20:59
Well, that's what odd to me too.

When I search I see multiple files containing `getBrowserIntent` one for each build flavor all inside of app/build/generated/ksp/{buildFlavor}/kotlin/{packageName}/RootModuleShowkaseExtensionFunctionsCodeGen.kt

Here's the contents of the file: 
`// This is an auto-generated file. Please do not edit/modify this file.
package <packagename>

import android.content.Context
import android.content.Intent
import com.airbnb.android.showkase.models.Showkase
import com.airbnb.android.showkase.models.ShowkaseElementsMetadata
import com.airbnb.android.showkase.models.ShowkaseProvider
import com.airbnb.android.showkase.ui.ShowkaseBrowserActivity

/**
 * Helper function that's autogenerated and gives you an intent to start the ShowkaseBrowser.
 */
public fun Showkase.getBrowserIntent(context: Context): Intent {
    val intent = Intent(context, ShowkaseBrowserActivity::class.java)
    intent.putExtra("SHOWKASE_ROOT_MODULE", "<packageName>.RootModule")
    return intent
}

/**
 * Helper function that's give's you access to Showkase metadata. This contains data about the
 * composables, colors and typography in your codebase that's rendered in showakse.
 */
public fun Showkase.getMetadata(): ShowkaseElementsMetadata {
    try {
      val showkaseComponentProvider =
          Class.forName("<packageName>.RootModuleCodegen").newInstance() as
          ShowkaseProvider
      return showkaseComponentProvider.metadata()
    } catch(exception: ClassNotFoundException) {
      error("The class wasn't generated correctly. Make sure that you have setup Showkase correctly by following the steps here - https://github.com/airbnb/Showkase#Installation.")
    }
}
`

**Comment by zaaaach** [comment] 2022-09-20 21:07
Yeah, it looks like because I had put the activity I was trying to access `getBrowserIntent` in a different package, but the same module. Didn't realize it was that granular.

**Comment by vinaygaba** [comment] 2022-09-23 03:27
@zaaaach seems like you've identified the root cause and were able to resolve it so I'll go ahead and close this issue

**Closed by vinaygaba** 2022-09-23 03:27 UTC
